/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline-variant": "#3b4861",
        "surface-container-low": "#02132b",
        "on-error-container": "#ffa8a3",
        "on-error": "#490006",
        "on-primary-fixed-variant": "#004c5e",
        "primary-fixed": "#00d2ff",
        "on-surface": "#dbe6ff",
        "surface-bright": "#152c4e",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#9eabc8",
        "on-primary-container": "#004253",
        "error-dim": "#d7383b",
        "secondary-container": "#00677d",
        "primary-container": "#00d2ff",
        "inverse-primary": "#00687f",
        "background": "#010e24",
        "on-tertiary-container": "#f8f1ff",
        "error-container": "#9f0519",
        "secondary-fixed-dim": "#59d2f5",
        "surface-variant": "#102645",
        "inverse-surface": "#f9f9ff",
        "secondary-dim": "#52cdef",
        "inverse-on-surface": "#48556e",
        "on-secondary-fixed": "#003a47",
        "secondary-fixed": "#78dfff",
        "primary": "#72dcff",
        "tertiary-fixed-dim": "#b190ff",
        "tertiary-container": "#7000ff",
        "tertiary-fixed": "#bda1ff",
        "primary-fixed-dim": "#00c3ed",
        "on-secondary-container": "#edfaff",
        "on-background": "#dbe6ff",
        "error": "#ff716c",
        "on-tertiary-fixed": "#1f0052",
        "secondary": "#63dbfe",
        "surface-tint": "#72dcff",
        "outline": "#687690",
        "on-secondary-fixed-variant": "#00586b",
        "surface": "#010e24",
        "tertiary": "#ac89ff",
        "on-primary-fixed": "#002c38",
        "primary-dim": "#00c3ed",
        "on-tertiary": "#290067",
        "surface-container": "#061934",
        "surface-dim": "#010e24",
        "surface-container-highest": "#102645",
        "on-primary": "#004c5e",
        "tertiary-dim": "#874cff",
        "on-secondary": "#004b5b",
        "surface-container-high": "#0b203d",
        "on-tertiary-fixed-variant": "#4700a7"
      },
      "fontFamily": {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
