serverAddr = "120.55.189.202"
serverPort = 7000

auth.method = "token"
auth.token = "13fb63f29d35470ab755696045baa497f1ccbabbcaf841033724dfd81f7bf5be"

transport.tls.enable = true

[[proxies]]
name = "ski-streamlit"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8503
remotePort = 8080
